"""
Recommendation service orchestrating AI-powered music discovery.

This is the core service that coordinates between:
- Ollama (LLM for generating recommendations)
- ChromaDB (user preferences for registered users)
- MCP YouTube Music client (enriching recommendations with video data)
- Last.fm API (for song tags and similar tracks)
- Audio Analysis (CLAP model for mood extraction from unidentified audio)
"""
import uuid
import logging
from typing import List, Dict, Any, Optional, Literal
from dataclasses import dataclass, asdict

from app.services.ollama_client import (
    get_ollama_client,
    OllamaClient,
    SongRecommendation,
    PromptTemplates
)
from app.db.chromadb_client import get_chromadb_client, ChromaDBClient
from app.mcp.client import get_mcp_client, MCPYouTubeMusicClient, YouTubeMusicSong
from app.services.lastfm_client import get_lastfm_client, LastFmClient
from app.services.audio_analysis import analyze_audio, get_search_queries_from_audio
from app.core.config import settings

# Langfuse for observability
try:
    from langfuse import Langfuse
    LANGFUSE_AVAILABLE = True
except ImportError:
    LANGFUSE_AVAILABLE = False
    Langfuse = None

logger = logging.getLogger(__name__)

# Configuration
RECOMMENDATIONS_PER_REQUEST = 20  # Number of songs to return per request


@dataclass
class EnrichedRecommendation:
    """A song recommendation enriched with YouTube Music data."""
    title: str
    artist: str
    reason: Optional[str] = None
    genre: Optional[str] = None
    mood: Optional[str] = None
    # YouTube Music data
    video_id: Optional[str] = None
    album: Optional[str] = None
    duration: Optional[str] = None
    thumbnail_url: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    @classmethod
    def from_recommendation_and_youtube(
        cls,
        rec: SongRecommendation,
        yt_song: Optional[YouTubeMusicSong]
    ) -> "EnrichedRecommendation":
        """Create from LLM recommendation and YouTube Music data."""
        return cls(
            title=yt_song.title if yt_song and yt_song.video_id else rec.title,
            artist=yt_song.artist if yt_song and yt_song.video_id else rec.artist,
            reason=rec.reason,
            genre=rec.genre,
            mood=rec.mood,
            video_id=yt_song.video_id if yt_song else None,
            album=yt_song.album if yt_song else None,
            duration=yt_song.duration if yt_song else None,
            thumbnail_url=yt_song.thumbnail_url if yt_song else None
        )


@dataclass
class RecommendationRequest:
    """Request for music recommendations."""
    input_type: Literal["mood", "audio", "combined", "audio_analysis"]
    # For mood-based
    mood_text: Optional[str] = None
    # For audio-based (identified song - Case 2)
    song_title: Optional[str] = None
    song_artist: Optional[str] = None
    song_genre: Optional[str] = None
    # For audio_analysis (unidentified song - Case 3)
    audio_mood_tags: Optional[List[str]] = None
    audio_genre_tags: Optional[List[str]] = None
    audio_tempo: Optional[str] = None  # "slow", "moderate", "fast"
    audio_energy: Optional[str] = None  # "low", "medium", "high"
    audio_search_queries: Optional[List[str]] = None  # Pre-generated by CLAP
    # Pagination for "Load more" - list of video_ids to exclude
    previous_songs: Optional[List[str]] = None  # video_ids already shown to user
    # Session info
    session_id: Optional[str] = None


@dataclass
class RecommendationResponse:
    """Response containing recommendations."""
    recommendations: List[EnrichedRecommendation]
    input_type: str
    session_id: str
    is_continuation: bool = False
    used_chromadb: bool = False
    chromadb_info: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "recommendations": [r.to_dict() for r in self.recommendations],
            "input_type": self.input_type,
            "session_id": self.session_id,
            "is_continuation": self.is_continuation,
            "used_chromadb": self.used_chromadb,
            "chromadb_info": self.chromadb_info
        }


class RecommendationService:
    """
    Core service for generating music recommendations.
    
    Handles the complete flow:
    1. Build appropriate system prompt based on user type
    2. Generate recommendations via Ollama
    3. Filter against dislikes (for registered users)
    4. Enrich with YouTube Music data
    5. Return formatted response
    """
    
    def __init__(self):
        self.ollama: OllamaClient = get_ollama_client()
        self.chromadb: ChromaDBClient = get_chromadb_client()
        self.mcp_client: MCPYouTubeMusicClient = get_mcp_client()
        self.lastfm: LastFmClient = get_lastfm_client()
        
        # Initialize Langfuse for observability (non-LLM flows)
        self.langfuse = None
        if LANGFUSE_AVAILABLE and settings.LANGFUSE_PUBLIC_KEY and settings.LANGFUSE_SECRET_KEY:
            try:
                self.langfuse = Langfuse(
                    public_key=settings.LANGFUSE_PUBLIC_KEY,
                    secret_key=settings.LANGFUSE_SECRET_KEY,
                    host=settings.LANGFUSE_HOST
                )
                logger.info("Langfuse initialized in RecommendationService")
            except Exception as e:
                logger.warning(f"Failed to initialize Langfuse: {e}")
    
    async def get_recommendations(
        self,
        request: RecommendationRequest,
        user_id: Optional[uuid.UUID] = None,
        youtube_auth_headers: Optional[str] = None
    ) -> RecommendationResponse:
        """
        Generate music recommendations based on user input.
        
        Args:
            request: The recommendation request
            user_id: UUID of registered user (None for guests)
            youtube_auth_headers: Optional YouTube Music auth for enrichment
            
        Returns:
            RecommendationResponse with enriched songs
        """
        # Generate session ID if not provided
        session_id = request.session_id or str(uuid.uuid4())
        
        # Track ChromaDB usage
        used_chromadb = False
        chromadb_info = None
        
        # CASE 2: Audio identified (song recognized)
        if request.input_type == "audio" and request.song_title and request.song_artist:
            return await self._get_recommendations_from_youtube(
                request, user_id, youtube_auth_headers, session_id
            )
        
        # CASE 3: Audio NOT identified (CLAP analysis)
        if request.input_type == "audio_analysis" and request.audio_mood_tags:
            return await self._get_recommendations_from_audio_analysis(
                request, user_id, youtube_auth_headers, session_id
            )
        
        # CASE 1: Mood/text-based requests
        return await self._get_recommendations_from_ollama(
            request, user_id, youtube_auth_headers, session_id
        )
    
    async def _get_recommendations_from_youtube(
        self,
        request: RecommendationRequest,
        user_id: Optional[uuid.UUID],
        youtube_auth_headers: Optional[str],
        session_id: str
    ) -> RecommendationResponse:
        """
        Get recommendations for an identified song.
        
        CASE 2 - Identified Song:
        - Logged-in user: ChromaDB preferences → LLM generates queries → YouTube Music
        - Guest user: Direct YouTube Music + Last.fm (no LLM, no preferences)
        """
        # Start Langfuse trace
        trace = None
        if self.langfuse:
            try:
                trace = self.langfuse.trace(
                    name="recommendations_from_identified_song",
                    input={
                        "song_title": request.song_title,
                        "song_artist": request.song_artist,
                        "song_genre": request.song_genre,
                        "session_id": session_id
                    },
                    metadata={
                        "flow": "Case 2 - Identified Song",
                        "user_id": str(user_id) if user_id else "guest",
                        "method": "llm_with_preferences" if user_id else "direct_youtube"
                    }
                )
            except Exception as e:
                logger.warning(f"Langfuse trace error: {e}")
        
        # LOGGED-IN USER: Use LLM with ChromaDB preferences
        if user_id:
            return await self._get_recommendations_from_identified_song_with_llm(
                request, user_id, youtube_auth_headers, session_id, trace
            )
        
        # GUEST USER: Direct YouTube Music + Last.fm
        return await self._get_recommendations_from_identified_song_direct(
            request, None, youtube_auth_headers, session_id, trace
        )
    
    async def _get_recommendations_from_identified_song_with_llm(
        self,
        request: RecommendationRequest,
        user_id: uuid.UUID,
        youtube_auth_headers: Optional[str],
        session_id: str,
        trace: Optional[Any] = None
    ) -> RecommendationResponse:
        """
        Case 2 for LOGGED-IN users:
        1. Get user preferences from ChromaDB
        2. Build prompt with identified song + user preferences
        3. LLM generates personalized search queries
        4. Search YouTube Music
        5. Filter dislikes
        """
        import asyncio
        used_chromadb = False
        chromadb_info = None
        
        try:
            # Step 1: Get user preferences from ChromaDB
            preferences_span = None
            if trace:
                try:
                    preferences_span = trace.span(
                        name="get_chromadb_preferences",
                        input={"user_id": str(user_id)}
                    )
                except Exception:
                    pass
            
            system_prompt, has_preferences = await self._build_system_prompt(user_id)
            
            if preferences_span:
                try:
                    preferences_span.end(output={"has_preferences": has_preferences})
                except Exception:
                    pass
            
            if has_preferences:
                used_chromadb = True
                chromadb_info = "Used preferences for personalized recommendations"
            
            # Step 2: Get Last.fm tags for additional context
            lastfm_tags = []
            if self.lastfm.is_configured:
                try:
                    lastfm_tags = await self.lastfm.get_track_tags(
                        request.song_title, request.song_artist
                    )
                    logger.info(f"Last.fm tags for '{request.song_title}': {lastfm_tags}")
                except Exception as e:
                    logger.warning(f"Last.fm tags failed: {e}")
            
            # Step 3: Build user prompt with song + Last.fm context
            song_context = f"Find songs similar to '{request.song_title}' by {request.song_artist}"
            if request.song_genre:
                song_context += f" (Genre: {request.song_genre})"
            if lastfm_tags:
                song_context += f". This song has these vibes: {', '.join(lastfm_tags[:5])}"
            
            # Step 4: LLM generates search queries with user preferences
            llm_span = None
            if trace:
                try:
                    llm_span = trace.span(
                        name="llm_generate_queries",
                        input={
                            "song_context": song_context,
                            "has_preferences": has_preferences,
                            "lastfm_tags": lastfm_tags
                        }
                    )
                except Exception:
                    pass
            
            search_queries = await self.ollama.extract_search_queries(
                song_context,
                system_prompt=system_prompt
            )
            
            if llm_span:
                try:
                    llm_span.end(output={"queries": search_queries})
                except Exception:
                    pass
            
            logger.info(f"LLM generated queries for identified song: {search_queries}")
            
            # Step 5: Search YouTube Music for each query
            yt_span = None
            if trace:
                try:
                    yt_span = trace.span(
                        name="youtube_music_search",
                        input={"queries": search_queries}
                    )
                except Exception:
                    pass
            
            enriched = []
            # Include previous songs to avoid duplicates on "Load More"
            seen_video_ids = set(request.previous_songs or [])
            
            for query in search_queries:
                try:
                    results = await self.mcp_client.search_songs(
                        query, limit=6, auth_headers=youtube_auth_headers
                    )
                    for song in results:
                        if song.video_id and song.video_id not in seen_video_ids:
                            seen_video_ids.add(song.video_id)
                            enriched.append(EnrichedRecommendation(
                                title=song.title,
                                artist=song.artist,
                                reason=f"Similar to {request.song_title}",
                                genre=request.song_genre,
                                mood=", ".join(lastfm_tags[:3]) if lastfm_tags else None,
                                video_id=song.video_id,
                                album=song.album,
                                duration=song.duration,
                                thumbnail_url=song.thumbnail_url
                            ))
                except Exception as e:
                    logger.warning(f"YouTube search failed for '{query}': {e}")
            
            if yt_span:
                try:
                    yt_span.end(output={"songs_found": len(enriched)})
                except Exception:
                    pass
            
            # Step 6: Filter dislikes
            if enriched:
                enriched, filtered_count, _ = await self._filter_enriched_dislikes(
                    user_id, enriched
                )
                if filtered_count > 0:
                    chromadb_info = f"{chromadb_info} | Blocked {filtered_count} disliked"
            
            # Log final output
            if trace:
                try:
                    trace.update(output={
                        "method": "llm_with_preferences",
                        "recommendations_count": len(enriched[:RECOMMENDATIONS_PER_REQUEST]),
                        "used_chromadb": used_chromadb,
                        "lastfm_tags": lastfm_tags,
                        "llm_queries": search_queries
                    })
                    self.langfuse.flush()
                except Exception:
                    pass
            
            return RecommendationResponse(
                recommendations=enriched[:RECOMMENDATIONS_PER_REQUEST],
                input_type=request.input_type,
                session_id=session_id,
                is_continuation=bool(request.previous_songs),
                used_chromadb=used_chromadb,
                chromadb_info=chromadb_info
            )
            
        except Exception as e:
            logger.error(f"LLM-based recommendations failed: {e}")
            if trace:
                try:
                    trace.update(output={"error": str(e), "fallback": "direct_youtube"})
                    self.langfuse.flush()
                except Exception:
                    pass
            # Fallback to direct YouTube method
            return await self._get_recommendations_from_identified_song_direct(
                request, user_id, youtube_auth_headers, session_id, trace
            )
    
    async def _get_recommendations_from_identified_song_direct(
        self,
        request: RecommendationRequest,
        user_id: Optional[uuid.UUID],
        youtube_auth_headers: Optional[str],
        session_id: str,
        trace: Optional[Any] = None
    ) -> RecommendationResponse:
        """
        Case 2 for GUEST users:
        Direct YouTube Music + Last.fm without LLM or preferences.
        """
        used_chromadb = False
        chromadb_info = None
        lastfm_tags = []
        
        try:
            # Step 1: Find the identified song on YouTube Music
            query = f"{request.song_title} {request.song_artist}"
            
            # Log YouTube search span
            yt_search_span = None
            if trace:
                try:
                    yt_search_span = trace.span(
                        name="youtube_music_search",
                        input={"query": query}
                    )
                except Exception:
                    pass
            
            search_results = await self.mcp_client.search_songs(
                query, limit=1, auth_headers=youtube_auth_headers
            )
            
            if yt_search_span:
                try:
                    yt_search_span.end(output={
                        "found": bool(search_results and search_results[0].video_id),
                        "video_id": search_results[0].video_id if search_results else None
                    })
                except Exception:
                    pass
            
            if not search_results or not search_results[0].video_id:
                # Fallback to Ollama if song not found on YouTube Music
                if trace:
                    try:
                        trace.update(output={"fallback": "ollama", "reason": "song not found on YouTube Music"})
                        self.langfuse.flush()
                    except Exception:
                        pass
                return await self._get_recommendations_from_ollama(
                    request, user_id, youtube_auth_headers, session_id
                )
            
            source_video_id = search_results[0].video_id
            
            # Step 2: Get tags from Last.fm (in parallel with YT recommendations)
            import asyncio
            
            async def get_lastfm_tags():
                if self.lastfm.is_configured:
                    return await self.lastfm.get_track_tags(
                        request.song_title, request.song_artist
                    )
                return []
            
            async def get_yt_recs():
                return await self.mcp_client.get_recommendations(
                    video_id=source_video_id,
                    limit=10,
                    auth_headers=youtube_auth_headers
                )
            
            # Log parallel fetch span
            parallel_span = None
            if trace:
                try:
                    parallel_span = trace.span(
                        name="parallel_fetch_lastfm_youtube",
                        input={"source_video_id": source_video_id}
                    )
                except Exception:
                    pass
            
            # Run in parallel
            lastfm_tags, yt_recommendations = await asyncio.gather(
                get_lastfm_tags(),
                get_yt_recs()
            )
            
            if parallel_span:
                try:
                    parallel_span.end(output={
                        "lastfm_tags": lastfm_tags,
                        "yt_recommendations_count": len(yt_recommendations) if yt_recommendations else 0
                    })
                except Exception:
                    pass
            
            logger.info(f"Last.fm tags for '{request.song_title}': {lastfm_tags}")
            
            # Step 3: Convert YT recommendations to enriched format
            enriched = []
            # Include previous songs to avoid duplicates on "Load More"
            seen_video_ids = set(request.previous_songs or [])
            
            if yt_recommendations:
                for song in yt_recommendations:
                    if song.video_id and song.video_id not in seen_video_ids:
                        seen_video_ids.add(song.video_id)
                        enriched.append(EnrichedRecommendation(
                            title=song.title,
                            artist=song.artist,
                            reason=f"Similar to {request.song_title}",
                            genre=request.song_genre,
                            mood=", ".join(lastfm_tags[:3]) if lastfm_tags else None,
                            video_id=song.video_id,
                            album=song.album,
                            duration=song.duration,
                            thumbnail_url=song.thumbnail_url
                        ))
            
            # Step 4: If we have Last.fm tags, search for more songs using those tags
            if lastfm_tags and len(enriched) < RECOMMENDATIONS_PER_REQUEST:
                # Build search queries from tags
                tag_queries = []
                for tag in lastfm_tags[:4]:
                    tag_queries.append(f"{tag} music")
                    if request.song_genre:
                        tag_queries.append(f"{tag} {request.song_genre}")
                
                # Log tag search span
                tag_search_span = None
                if trace:
                    try:
                        tag_search_span = trace.span(
                            name="lastfm_tag_search",
                            input={"tag_queries": tag_queries[:3], "lastfm_tags": lastfm_tags}
                        )
                    except Exception:
                        pass
                
                tag_search_results = []
                
                # Search YouTube Music for tag-based songs
                for query in tag_queries[:3]:  # Limit to 3 queries
                    try:
                        tag_results = await self.mcp_client.search_songs(
                            query, limit=3, auth_headers=youtube_auth_headers
                        )
                        tag_search_results.append({"query": query, "results": len(tag_results)})
                        for song in tag_results:
                            if song.video_id and song.video_id not in seen_video_ids:
                                seen_video_ids.add(song.video_id)
                                enriched.append(EnrichedRecommendation(
                                    title=song.title,
                                    artist=song.artist,
                                    reason=f"Matches: {query}",
                                    genre=request.song_genre,
                                    mood=", ".join(lastfm_tags[:3]),
                                    video_id=song.video_id,
                                    album=song.album,
                                    duration=song.duration,
                                    thumbnail_url=song.thumbnail_url
                                ))
                    except Exception as e:
                        logger.warning(f"Tag search failed for '{query}': {e}")
                        tag_search_results.append({"query": query, "error": str(e)})
                
                if tag_search_span:
                    try:
                        tag_search_span.end(output={
                            "searches": tag_search_results,
                            "new_recommendations": len(enriched) - len(seen_video_ids) + len(tag_search_results)
                        })
                    except Exception:
                        pass
            
            # If no recommendations at all, fallback to Ollama
            if not enriched:
                return await self._get_recommendations_from_ollama(
                    request, user_id, youtube_auth_headers, session_id
                )
            
            # Step 5: Filter dislikes for registered users
            if user_id:
                enriched, filtered_count, deprioritized_count = await self._filter_enriched_dislikes(
                    user_id, enriched
                )
                if filtered_count > 0 or deprioritized_count > 0:
                    used_chromadb = True
                    info_parts = ["Used for preferences"]
                    if filtered_count > 0:
                        info_parts.append(f"blocked {filtered_count} disliked")
                    chromadb_info = " + ".join(info_parts)
            
            # Add Last.fm info to response
            chromadb_info_parts = [chromadb_info] if chromadb_info else []
            if lastfm_tags:
                chromadb_info_parts.append(f"Last.fm tags: {', '.join(lastfm_tags[:5])}")
            
            final_response = RecommendationResponse(
                recommendations=enriched[:RECOMMENDATIONS_PER_REQUEST],
                input_type=request.input_type,
                session_id=session_id,
                is_continuation=bool(request.previous_songs),
                used_chromadb=used_chromadb,
                chromadb_info=" | ".join(chromadb_info_parts) if chromadb_info_parts else None
            )
            
            # Log final output to Langfuse
            if trace:
                try:
                    trace.update(output={
                        "recommendations_count": len(enriched[:RECOMMENDATIONS_PER_REQUEST]),
                        "lastfm_tags": lastfm_tags,
                        "used_chromadb": used_chromadb,
                        "recommendations": [
                            {"title": r.title, "artist": r.artist, "video_id": r.video_id}
                            for r in enriched[:RECOMMENDATIONS_PER_REQUEST]
                        ]
                    })
                    self.langfuse.flush()
                except Exception as e:
                    logger.warning(f"Langfuse output error: {e}")
            
            return final_response
            
        except Exception as e:
            # On any error, fallback to Ollama
            logger.error(f"YouTube Music recommendations failed: {e}")
            if trace:
                try:
                    trace.update(
                        output={"fallback": "ollama", "error": str(e)},
                        level="ERROR"
                    )
                    self.langfuse.flush()
                except Exception:
                    pass
            return await self._get_recommendations_from_ollama(
                request, user_id, youtube_auth_headers, session_id
            )
    
    async def _get_recommendations_from_audio_analysis(
        self,
        request: RecommendationRequest,
        user_id: Optional[uuid.UUID],
        youtube_auth_headers: Optional[str],
        session_id: str
    ) -> RecommendationResponse:
        """
        CASE 3: Get recommendations from CLAP audio analysis (unidentified song).
        
        - Logged-in user: CLAP data + ChromaDB preferences → LLM → YouTube Music
        - Guest user: CLAP search_queries → YouTube Music directly
        """
        # Start Langfuse trace
        trace = None
        if self.langfuse:
            try:
                trace = self.langfuse.trace(
                    name="recommendations_from_audio_analysis",
                    input={
                        "mood_tags": request.audio_mood_tags,
                        "genre_tags": request.audio_genre_tags,
                        "tempo": request.audio_tempo,
                        "energy": request.audio_energy,
                        "clap_queries": request.audio_search_queries,
                        "session_id": session_id
                    },
                    metadata={
                        "flow": "Case 3 - Unidentified Audio (CLAP)",
                        "user_id": str(user_id) if user_id else "guest",
                        "method": "llm_with_preferences" if user_id else "direct_clap_queries"
                    }
                )
            except Exception as e:
                logger.warning(f"Langfuse trace error: {e}")
        
        # LOGGED-IN USER: CLAP + ChromaDB preferences → LLM → YouTube
        if user_id:
            return await self._get_audio_analysis_recs_with_llm(
                request, user_id, youtube_auth_headers, session_id, trace
            )
        
        # GUEST USER: Use CLAP search_queries directly → YouTube
        return await self._get_audio_analysis_recs_direct(
            request, youtube_auth_headers, session_id, trace
        )
    
    async def _get_audio_analysis_recs_with_llm(
        self,
        request: RecommendationRequest,
        user_id: uuid.UUID,
        youtube_auth_headers: Optional[str],
        session_id: str,
        trace: Optional[Any] = None
    ) -> RecommendationResponse:
        """
        Case 3 for LOGGED-IN users:
        CLAP analysis + user preferences → LLM generates personalized queries → YouTube
        """
        used_chromadb = False
        chromadb_info = None
        
        try:
            # Step 1: Get user preferences from ChromaDB
            preferences_span = None
            if trace:
                try:
                    preferences_span = trace.span(
                        name="get_chromadb_preferences",
                        input={"user_id": str(user_id)}
                    )
                except Exception:
                    pass
            
            system_prompt, has_preferences = await self._build_system_prompt(user_id)
            
            if preferences_span:
                try:
                    preferences_span.end(output={"has_preferences": has_preferences})
                except Exception:
                    pass
            
            if has_preferences:
                used_chromadb = True
                chromadb_info = "Used preferences for personalized recommendations"
            
            # Step 2: Build context from CLAP analysis
            clap_context = self._build_clap_context(request)
            
            # Step 3: LLM generates search queries with CLAP data + user preferences
            llm_span = None
            if trace:
                try:
                    llm_span = trace.span(
                        name="llm_generate_queries_from_clap",
                        input={
                            "clap_context": clap_context,
                            "has_preferences": has_preferences
                        }
                    )
                except Exception:
                    pass
            
            search_queries = await self.ollama.extract_search_queries(
                clap_context,
                system_prompt=system_prompt
            )
            
            if llm_span:
                try:
                    llm_span.end(output={"queries": search_queries})
                except Exception:
                    pass
            
            logger.info(f"LLM generated queries from CLAP analysis: {search_queries}")
            
            # Step 4: Search YouTube Music
            enriched = await self._search_youtube_with_queries(
                search_queries, youtube_auth_headers, request, trace
            )
            
            # Step 5: Filter dislikes
            if enriched:
                enriched, filtered_count, _ = await self._filter_enriched_dislikes(
                    user_id, enriched
                )
                if filtered_count > 0:
                    chromadb_info = f"{chromadb_info} | Blocked {filtered_count} disliked"
            
            # Log final output
            if trace:
                try:
                    trace.update(output={
                        "method": "llm_with_preferences",
                        "recommendations_count": len(enriched[:RECOMMENDATIONS_PER_REQUEST]),
                        "used_chromadb": used_chromadb,
                        "clap_context": clap_context,
                        "llm_queries": search_queries
                    })
                    self.langfuse.flush()
                except Exception:
                    pass
            
            return RecommendationResponse(
                recommendations=enriched[:RECOMMENDATIONS_PER_REQUEST],
                input_type="audio_analysis",
                session_id=session_id,
                is_continuation=bool(request.previous_songs),
                used_chromadb=used_chromadb,
                chromadb_info=chromadb_info
            )
            
        except Exception as e:
            logger.error(f"LLM-based audio analysis recommendations failed: {e}")
            if trace:
                try:
                    trace.update(output={"error": str(e), "fallback": "direct_clap"})
                    self.langfuse.flush()
                except Exception:
                    pass
            # Fallback to direct CLAP queries
            return await self._get_audio_analysis_recs_direct(
                request, youtube_auth_headers, session_id, trace
            )
    
    async def _get_audio_analysis_recs_direct(
        self,
        request: RecommendationRequest,
        youtube_auth_headers: Optional[str],
        session_id: str,
        trace: Optional[Any] = None
    ) -> RecommendationResponse:
        """
        Case 3 for GUEST users:
        Use CLAP-generated search_queries directly → YouTube Music
        """
        try:
            # Use pre-generated CLAP queries or build from tags
            search_queries = request.audio_search_queries
            if not search_queries:
                # Build queries from CLAP tags
                search_queries = self._build_queries_from_clap_tags(request)
            
            if trace:
                try:
                    span = trace.span(
                        name="direct_clap_search",
                        input={"queries": search_queries}
                    )
                except Exception:
                    pass
            
            logger.info(f"Using CLAP queries directly: {search_queries}")
            
            # Search YouTube Music
            enriched = await self._search_youtube_with_queries(
                search_queries, youtube_auth_headers, request, trace
            )
            
            # Log final output
            if trace:
                try:
                    trace.update(output={
                        "method": "direct_clap_queries",
                        "recommendations_count": len(enriched[:RECOMMENDATIONS_PER_REQUEST]),
                        "queries_used": search_queries
                    })
                    self.langfuse.flush()
                except Exception:
                    pass
            
            return RecommendationResponse(
                recommendations=enriched[:RECOMMENDATIONS_PER_REQUEST],
                input_type="audio_analysis",
                session_id=session_id,
                is_continuation=bool(request.previous_songs),
                used_chromadb=False,
                chromadb_info="CLAP audio analysis"
            )
            
        except Exception as e:
            logger.error(f"Direct CLAP recommendations failed: {e}")
            return RecommendationResponse(
                recommendations=[],
                input_type="audio_analysis",
                session_id=session_id,
                is_continuation=False,
                used_chromadb=False
            )
    
    def _build_clap_context(self, request: RecommendationRequest) -> str:
        """Build a text description from CLAP analysis for LLM."""
        parts = []
        
        if request.audio_mood_tags:
            parts.append(f"Mood: {', '.join(request.audio_mood_tags)}")
        if request.audio_genre_tags:
            parts.append(f"Genre: {', '.join(request.audio_genre_tags)}")
        if request.audio_tempo:
            parts.append(f"Tempo: {request.audio_tempo}")
        if request.audio_energy:
            parts.append(f"Energy: {request.audio_energy}")
        
        return f"Find music matching this audio analysis: {'. '.join(parts)}"
    
    def _build_queries_from_clap_tags(self, request: RecommendationRequest) -> List[str]:
        """Build search queries from CLAP tags when pre-generated queries not available."""
        queries = []
        
        mood_tags = request.audio_mood_tags or []
        genre_tags = request.audio_genre_tags or []
        
        # Mood + genre combinations
        for mood in mood_tags[:3]:
            queries.append(f"{mood} music")
            for genre in genre_tags[:2]:
                queries.append(f"{mood} {genre}")
        
        # Genre-only queries
        for genre in genre_tags[:2]:
            queries.append(f"{genre} songs")
        
        # Tempo/energy-based
        if request.audio_tempo == "slow" and request.audio_energy == "low":
            queries.extend(["slow relaxing music", "chill ballads"])
        elif request.audio_tempo == "fast" and request.audio_energy == "high":
            queries.extend(["upbeat energetic music", "party songs"])
        
        return queries[:8]
    
    async def _search_youtube_with_queries(
        self,
        search_queries: List[str],
        youtube_auth_headers: Optional[str],
        request: RecommendationRequest,
        trace: Optional[Any] = None
    ) -> List[EnrichedRecommendation]:
        """Search YouTube Music with a list of queries and return enriched results."""
        enriched = []
        # Include previous songs to avoid duplicates on "Load More"
        seen_video_ids = set(request.previous_songs or [])
        
        yt_span = None
        if trace:
            try:
                yt_span = trace.span(
                    name="youtube_music_search",
                    input={"queries": search_queries}
                )
            except Exception:
                pass
        
        for query in search_queries:
            try:
                results = await self.mcp_client.search_songs(
                    query, limit=6, auth_headers=youtube_auth_headers
                )
                for song in results:
                    if song.video_id and song.video_id not in seen_video_ids:
                        seen_video_ids.add(song.video_id)
                        
                        # Build reason from CLAP data
                        mood_str = ", ".join(request.audio_mood_tags[:2]) if request.audio_mood_tags else None
                        
                        enriched.append(EnrichedRecommendation(
                            title=song.title,
                            artist=song.artist,
                            reason=f"Matches: {mood_str}" if mood_str else f"Matches: {query}",
                            genre=request.audio_genre_tags[0] if request.audio_genre_tags else None,
                            mood=mood_str,
                            video_id=song.video_id,
                            album=song.album,
                            duration=song.duration,
                            thumbnail_url=song.thumbnail_url
                        ))
            except Exception as e:
                logger.warning(f"YouTube search failed for '{query}': {e}")
        
        if yt_span:
            try:
                yt_span.end(output={"songs_found": len(enriched)})
            except Exception:
                pass
        
        return enriched
    
    async def _filter_enriched_dislikes(
        self,
        user_id: uuid.UUID,
        enriched: List[EnrichedRecommendation]
    ) -> tuple[List[EnrichedRecommendation], int, int]:
        """
        Filter and deprioritize disliked songs from enriched recommendations.
        
        1. REMOVE exact matches (same video_id or same title+artist)
        2. DEPRIORITIZE songs similar to dislikes (move to end of list)
        
        Returns:
            Tuple of (filtered_recommendations, removed_count, deprioritized_count)
        """
        # Step 1: Remove exact disliked songs
        filtered = []
        filtered_count = 0
        
        for rec in enriched:
            is_disliked = await self.chromadb.check_if_disliked(
                user_id,
                rec.title,
                rec.artist,
                rec.video_id
            )
            if is_disliked:
                filtered_count += 1
            else:
                filtered.append(rec)
        
        # Step 2: Deprioritize songs similar to dislikes
        if filtered:
            filtered, deprioritized_count = await self._deprioritize_similar_to_dislikes(
                user_id, filtered
            )
        else:
            deprioritized_count = 0
        
        return filtered, filtered_count, deprioritized_count
    
    async def _get_recommendations_from_ollama(
        self,
        request: RecommendationRequest,
        user_id: Optional[uuid.UUID],
        youtube_auth_headers: Optional[str],
        session_id: str
    ) -> RecommendationResponse:
        """
        Get recommendations using Ollama + YouTube Music hybrid approach.
        
        Ollama interprets the user's mood/text and generates search queries,
        then YouTube Music finds real songs matching those queries.
        
        For logged-in users: includes ChromaDB preferences in the LLM prompt.
        """
        import logging
        logger = logging.getLogger(__name__)
        
        # Track ChromaDB usage
        used_chromadb = False
        chromadb_info = None
        filtered_count = 0
        
        # Get the user's text query
        user_text = request.mood_text or ""
        if not user_text and request.song_title:
            user_text = f"songs similar to {request.song_title} by {request.song_artist}"
        
        if not user_text:
            # No text provided, return empty
            return RecommendationResponse(
                recommendations=[],
                input_type=request.input_type,
                session_id=session_id,
                is_continuation=False,
                used_chromadb=False
            )
        
        # Start Langfuse trace for mood-based recommendations
        trace = None
        if self.langfuse:
            try:
                trace = self.langfuse.trace(
                    name="recommendations_from_mood",
                    input={
                        "mood_text": user_text,
                        "session_id": session_id
                    },
                    metadata={
                        "flow": "Case 1 - Mood/Text Based",
                        "user_id": str(user_id) if user_id else "guest",
                        "has_previous_songs": bool(request.previous_songs)
                    }
                )
            except Exception as e:
                logger.warning(f"Langfuse trace error: {e}")
        
        try:
            # Step 1: Get user preferences from ChromaDB (for logged-in users)
            system_prompt = None
            if user_id:
                logger.info(f"[MOOD] Getting preferences for user_id: {user_id}")
                
                # Log preferences fetch to Langfuse
                preferences_span = None
                if trace:
                    try:
                        preferences_span = trace.span(
                            name="get_chromadb_preferences",
                            input={"user_id": str(user_id)}
                        )
                    except Exception:
                        pass
                
                system_prompt, has_preferences = await self._build_system_prompt(user_id)
                logger.info(f"[MOOD] has_preferences: {has_preferences}")
                
                if preferences_span:
                    try:
                        preferences_span.end(output={"has_preferences": has_preferences})
                    except Exception:
                        pass
                
                if has_preferences:
                    used_chromadb = True
                    chromadb_info = "Used preferences for personalized recommendations"
                    logger.info(f"[MOOD] Using ChromaDB preferences for user {user_id}")
                else:
                    logger.info(f"[MOOD] No preferences found for user {user_id}")
            
            # Step 2: Ollama extracts search queries from user's text (with preferences if available)
            logger.info(f"Extracting search queries from: {user_text}")
            
            # Log LLM call to Langfuse
            llm_span = None
            if trace:
                try:
                    llm_span = trace.span(
                        name="llm_extract_search_queries",
                        input={
                            "user_text": user_text,
                            "has_system_prompt": system_prompt is not None
                        }
                    )
                except Exception:
                    pass
            
            search_queries = await self.ollama.extract_search_queries(
                user_text,
                system_prompt=system_prompt
            )
            logger.info(f"Generated {len(search_queries)} search queries: {search_queries}")
            
            if llm_span:
                try:
                    llm_span.end(output={"queries": search_queries})
                except Exception:
                    pass
            
            # Step 2: Search YouTube Music for each query
            all_songs: List[YouTubeMusicSong] = []
            # Include previous songs to avoid duplicates on "Load More"
            seen_video_ids = set(request.previous_songs or [])
            
            for query in search_queries:
                try:
                    results = await self.mcp_client.search_songs(
                        query, 
                        limit=6, 
                        auth_headers=youtube_auth_headers
                    )
                    for song in results:
                        # Deduplicate by video_id
                        if song.video_id and song.video_id not in seen_video_ids:
                            seen_video_ids.add(song.video_id)
                            all_songs.append(song)
                except Exception as e:
                    logger.warning(f"Search failed for query '{query}': {e}")
                    continue
            
            logger.info(f"Found {len(all_songs)} unique songs from YouTube Music")
            
            # Convert to enriched recommendations
            enriched = [
                EnrichedRecommendation(
                    title=song.title,
                    artist=song.artist,
                    reason=f"Matches: {user_text[:50]}...",
                    genre=None,
                    mood=None,
                    video_id=song.video_id,
                    album=song.album,
                    duration=song.duration,
                    thumbnail_url=song.thumbnail_url
                )
                for song in all_songs
            ]
            
            # Filter dislikes for registered users
            if user_id and enriched:
                enriched, filtered_count, _ = await self._filter_enriched_dislikes(
                    user_id, enriched
                )
                if filtered_count > 0:
                    used_chromadb = True
                    if chromadb_info:
                        chromadb_info = f"{chromadb_info} | Blocked {filtered_count} disliked"
                    else:
                        chromadb_info = f"Blocked {filtered_count} disliked songs"
            
            # Log final output to Langfuse
            if trace:
                try:
                    trace.update(output={
                        "recommendations_count": len(enriched[:RECOMMENDATIONS_PER_REQUEST]),
                        "used_chromadb": used_chromadb,
                        "search_queries": search_queries,
                        "recommendations": [
                            {"title": r.title, "artist": r.artist, "video_id": r.video_id}
                            for r in enriched[:RECOMMENDATIONS_PER_REQUEST]
                        ]
                    })
                    self.langfuse.flush()
                except Exception as e:
                    logger.warning(f"Langfuse output error: {e}")
            
            return RecommendationResponse(
                recommendations=enriched[:RECOMMENDATIONS_PER_REQUEST],
                input_type=request.input_type,
                session_id=session_id,
                is_continuation=bool(request.previous_songs),
                used_chromadb=used_chromadb,
                chromadb_info=chromadb_info
            )
            
        except Exception as e:
            logger.error(f"Hybrid recommendation failed: {e}")
            if trace:
                try:
                    trace.update(output={"error": str(e)}, level="ERROR")
                    self.langfuse.flush()
                except Exception:
                    pass
            # Fallback: direct YouTube Music search with user text
            try:
                results = await self.mcp_client.search_songs(
                    user_text, 
                    limit=10, 
                    auth_headers=youtube_auth_headers
                )
                enriched = [
                    EnrichedRecommendation(
                        title=song.title,
                        artist=song.artist,
                        reason="Direct search result",
                        video_id=song.video_id,
                        album=song.album,
                        duration=song.duration,
                        thumbnail_url=song.thumbnail_url
                    )
                    for song in results
                ]
                return RecommendationResponse(
                    recommendations=enriched,
                    input_type=request.input_type,
                    session_id=session_id,
                    is_continuation=False,
                    used_chromadb=False
                )
            except Exception:
                return RecommendationResponse(
                    recommendations=[],
                    input_type=request.input_type,
                    session_id=session_id,
                    is_continuation=False,
                    used_chromadb=False
                )
    
    async def _build_system_prompt(self, user_id: Optional[uuid.UUID]) -> tuple[str, bool]:
        """
        Build the system prompt based on user type.
        
        For registered users: includes preference context from ChromaDB
        For guests: generic discovery-focused prompt
        
        Returns:
            Tuple of (system_prompt, used_chromadb)
        """
        if user_id is None:
            # Guest user - no history
            return PromptTemplates.guest_user_prompt(), False
        
        # Registered user - get preferences
        try:
            logger.info(f"[BUILD_PROMPT] Fetching preferences for user_id: {user_id}")
            preferences = await self.chromadb.get_preference_summary(user_id)
            logger.info(f"[BUILD_PROMPT] preferences: {preferences}")
            dislikes = await self.chromadb.get_user_dislikes(user_id)
            logger.info(f"[BUILD_PROMPT] dislikes count: {len(dislikes)}")
            
            dislike_list = [
                f"{d.get('metadata', {}).get('song_title', '')} - {d.get('metadata', {}).get('artist', '')}"
                for d in dislikes
            ]
            
            # Check if we actually have preferences data (not just empty dict)
            has_preferences = (
                preferences.get("total_likes", 0) > 0 or 
                preferences.get("total_dislikes", 0) > 0 or 
                bool(dislike_list)
            )
            logger.info(f"[BUILD_PROMPT] has_preferences: {has_preferences} (likes={preferences.get('total_likes', 0)}, dislikes={preferences.get('total_dislikes', 0)})")
            
            return PromptTemplates.registered_user_prompt(preferences, dislike_list), has_preferences
        except Exception as e:
            # Fallback to guest prompt on error
            logger.error(f"[BUILD_PROMPT] Error getting preferences: {e}")
            return PromptTemplates.guest_user_prompt(), False
    
    def _build_user_prompt(self, request: RecommendationRequest) -> str:
        """Build the user prompt based on input type."""
        if request.input_type == "mood":
            return PromptTemplates.build_user_prompt_from_mood(
                request.mood_text or "upbeat and energetic"
            )
        elif request.input_type == "combined":
            # Combined prompt with both mood and song context
            return PromptTemplates.build_combined_prompt(
                mood=request.mood_text or "",
                title=request.song_title or "Unknown",
                artist=request.song_artist or "Unknown",
                genre=request.song_genre
            )
        else:  # audio
            return PromptTemplates.build_user_prompt_from_song(
                title=request.song_title or "Unknown",
                artist=request.song_artist or "Unknown",
                genre=request.song_genre
            )
    
    async def _deprioritize_similar_to_dislikes(
        self,
        user_id: uuid.UUID,
        recommendations: List[EnrichedRecommendation]
    ) -> tuple[List[EnrichedRecommendation], int]:
        """
        Deprioritize (but don't remove) songs similar to dislikes.
        
        Songs similar to dislikes are moved to the end of the list,
        but still shown. This allows discovery while respecting preferences.
        
        Returns:
            Tuple of (reordered recommendations, count of deprioritized songs)
        """
        if not recommendations:
            return recommendations, 0
        
        # Get similarity penalty scores
        songs_data = [
            {"title": rec.title, "artist": rec.artist}
            for rec in recommendations
        ]
        
        penalty_scores = await self.chromadb.get_dislike_similarity_scores(
            user_id,
            songs_data
        )
        
        # Pair recommendations with their penalty scores
        scored_recs = list(zip(recommendations, penalty_scores))
        
        # Count how many have significant penalties (> 0.2)
        deprioritized_count = sum(1 for _, score in scored_recs if score > 0.2)
        
        # Sort by penalty score (lowest penalty first = highest priority)
        scored_recs.sort(key=lambda x: x[1])
        
        # Extract sorted recommendations
        sorted_recs = [rec for rec, _ in scored_recs]
        
        return sorted_recs, deprioritized_count
    
    async def _enrich_with_youtube(
        self,
        recommendations: List[SongRecommendation],
        auth_headers: Optional[str]
    ) -> List[EnrichedRecommendation]:
        """
        Enrich recommendations with YouTube Music data.
        
        Searches for each song on YouTube Music and adds video IDs,
        thumbnails, and other metadata.
        """
        enriched = []
        
        # Prepare songs for batch search
        songs_to_search = [
            {"title": rec.title, "artist": rec.artist}
            for rec in recommendations
        ]
        
        # Get YouTube Music data
        try:
            youtube_songs = await self.mcp_client.enrich_songs_with_youtube_data(
                songs_to_search,
                auth_headers
            )
            
            # Combine LLM recommendations with YouTube data
            for i, rec in enumerate(recommendations):
                yt_song = youtube_songs[i] if i < len(youtube_songs) else None
                enriched.append(
                    EnrichedRecommendation.from_recommendation_and_youtube(rec, yt_song)
                )
        except Exception:
            # On error, return recommendations without YouTube data
            for rec in recommendations:
                enriched.append(
                    EnrichedRecommendation(
                        title=rec.title,
                        artist=rec.artist,
                        reason=rec.reason,
                        genre=rec.genre,
                        mood=rec.mood
                    )
                )
        
        return enriched
    
    async def record_feedback(
        self,
        user_id: uuid.UUID,
        song_title: str,
        artist: str,
        feedback_score: int,
        video_id: Optional[str] = None,
        genre: Optional[str] = None,
        mood_tags: Optional[List[str]] = None
    ) -> bool:
        """
        Record user feedback on a recommendation.
        
        Updates ChromaDB with the user's like/dislike for future
        recommendation personalization.
        
        Args:
            user_id: The user's UUID
            song_title: Title of the song
            artist: Artist name
            feedback_score: 1 for like, -1 for dislike
            video_id: Optional YouTube video ID
            genre: Optional genre
            mood_tags: Optional mood/vibe tags
            
        Returns:
            True if successful
        """
        from app.db.chromadb_client import MusicPreference
        
        preference = MusicPreference(
            song_title=song_title,
            artist=artist,
            genre=genre,
            mood_tags=mood_tags,
            feedback_score=feedback_score,
            youtube_video_id=video_id
        )
        
        try:
            await self.chromadb.add_preference(user_id, preference)
            return True
        except Exception:
            return False


# Singleton instance
_recommendation_service: Optional[RecommendationService] = None


def get_recommendation_service() -> RecommendationService:
    """Get the recommendation service singleton."""
    global _recommendation_service
    if _recommendation_service is None:
        _recommendation_service = RecommendationService()
    return _recommendation_service
